backend:
  name: github
  repo: markjoeljimenez/portfolio

media_folder: src/images/assets
public_folder: ../images/assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: tag, label: Tag, widget: string }
      - { name: path, label: Path }
  - name: projects
    label: Projects
    folder: src/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        fields:
          - { name: image, label: Cover Image, widget: image }
          - { name: date, label: Date, widget: date }
          - { name: path, label: Path, widget: string, default: "/projects/"}
          - { name: shortDescription, label: Short Description, widget: markdown }
          - { name: tools, label: Tools, widget: string }
          - { name: tag, label: Tag, widget: string }
          - name: "website"
            label: "Website"
            widget: "object"
            fields:
              - { name: websiteLink, label: Website Link, widget: string }
              - { name: websiteTitle, label: Website Title, widget: string }
              - { name: githubLink, label: Github Link, widget: string }
              - { name: githubTitle, label: Github Title, widget: string }
          - {label: "Featured", name: "featured", widget: "boolean", default: true}
      - label: "Styles"
        name: "styles"
        widget: "object"
        fields:
          - label: "Theme"
            name: "theme"
            widget: "select"
            default: "Default"
            options: ["Default", "Light", "Dark"]
          - {label: "Reverse", name: "reverse", widget: "boolean", default: false}