backend:
  name: github
  repo: markjoeljimenez/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: project
    label: Project
    folder: src/projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: string }