backend:
  name: github
  repo: markjoeljimenez/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: tag, label: Tag, widget: string }
  - name: project
    label: Project
    folder: src/projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: tag, label: Tag, widget: string }
      - { name: tools, label: Tools, widget: string }
      - { name: image, label: Cover Image, widget: image }